#!/usr/bin/env python3
"""Build Q2RTX override maps from ChatGPT Images 2 source PNG textures."""

from __future__ import annotations

import argparse
import pathlib
from typing import List, Sequence, Tuple

from PIL import Image


EMISSIVE_TEXTURES = {"technolights", "floor_0101"}


def write_tga(path: pathlib.Path, image: Image.Image) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.convert("RGBA").save(path, format="TGA")


def write_greyscale_tga(path: pathlib.Path, greyscale: Sequence[int], size: Tuple[int, int]) -> None:
    image = Image.new("RGBA", size)
    image.putdata([(value, value, value, 255) for value in greyscale])
    write_tga(path, image)


def pack_alpha(image: Image.Image, alpha: Sequence[int]) -> Image.Image:
    rgba = image.convert("RGBA")
    pixels = [(r, g, b, a) for (r, g, b, _old_a), a in zip(rgba.getdata(), alpha)]
    out = Image.new("RGBA", rgba.size)
    out.putdata(pixels)
    return out


def normal_from_image(image: Image.Image, strength: float, metalness: Sequence[int]) -> Image.Image:
    grey = image.convert("L")
    width, height = grey.size
    src = list(grey.getdata())
    pixels: List[Tuple[int, int, int, int]] = []
    for y in range(height):
        for x in range(width):
            left = src[y * width + max(0, x - 1)] / 255.0
            right = src[y * width + min(width - 1, x + 1)] / 255.0
            up = src[max(0, y - 1) * width + x] / 255.0
            down = src[min(height - 1, y + 1) * width + x] / 255.0
            dx = (left - right) * strength
            dy = (up - down) * strength
            nz = 1.0
            length = max((dx * dx + dy * dy + nz * nz) ** 0.5, 1e-6)
            nx = dx / length
            ny = dy / length
            nz /= length
            pixels.append((
                int((nx * 0.5 + 0.5) * 255),
                int((ny * 0.5 + 0.5) * 255),
                int((nz * 0.5 + 0.5) * 255),
                metalness[y * width + x],
            ))
    out = Image.new("RGBA", (width, height))
    out.putdata(pixels)
    return out


def emissive_from_image(image: Image.Image, name: str) -> Image.Image:
    rgba = image.convert("RGBA")
    pixels: List[Tuple[int, int, int, int]] = []
    for r, g, b, _a in rgba.getdata():
        if name == "floor_0101":
            keep = b >= max(r, g) * 0.85 and max(r, g, b) > 40
        else:
            keep = max(r, g, b) > 56 and (b > r * 1.05 or r > g * 1.15)
        if keep:
            pixels.append((min(255, r * 2), min(255, g * 2), min(255, b * 2), 255))
        else:
            pixels.append((0, 0, 0, 255))
    out = Image.new("RGBA", rgba.size)
    out.putdata(pixels)
    return out


def material_factors(name: str) -> Tuple[float, float, float]:
    lowered = name.lower()
    if lowered.startswith("floor_") or lowered in {"rocky", "stonewall", "brownstonestep"}:
        return 0.95, 0.0, 0.15
    if "metal" in lowered or "techno" in lowered or "door" in lowered or "pipe" in lowered:
        return 0.55, 0.15, 0.65
    return 0.75, 0.0, 0.35


def pbr_maps_from_image(image: Image.Image, name: str) -> Tuple[List[int], List[int]]:
    roughness, metalness, _specular = material_factors(name)
    rgba = image.convert("RGBA")
    lowered = name.lower()
    metallic_surface = (
        metalness > 0.0
        or "metal" in lowered
        or "techno" in lowered
        or "door" in lowered
        or "pipe" in lowered
    )
    roughness_values: List[int] = []
    metalness_values: List[int] = []
    for r, g, b, _a in rgba.getdata():
        luma = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255.0
        saturation = (max(r, g, b) - min(r, g, b)) / 255.0

        local_roughness = roughness + (0.5 - luma) * 0.12 + saturation * 0.05
        if name in EMISSIVE_TEXTURES and max(r, g, b) > 64:
            local_roughness -= 0.2
        local_roughness = max(0.05, min(1.0, local_roughness))

        local_metalness = metalness
        if metallic_surface:
            local_metalness += (luma - 0.35) * 0.25
            if saturation > 0.45:
                local_metalness *= 0.65
        else:
            local_metalness = 0.0
        local_metalness = max(0.0, min(1.0, local_metalness))

        roughness_values.append(round(local_roughness * 255))
        metalness_values.append(round(local_metalness * 255))
    return roughness_values, metalness_values


def write_materials(path: pathlib.Path, names: Sequence[str]) -> None:
    lines = [
        "# Generated by tools/build_q2rtx_pbr_from_image2.py",
        "# Q2RTX material overrides from ChatGPT Images 2 source textures.",
        "",
    ]
    for name in sorted(names):
        roughness, metalness, specular = material_factors(name)
        lines.append(f"ab3d2/{name},")
        lines.append(f"textures/ab3d2/{name}:")
        lines.append(f"    texture_base overrides/ab3d2/{name}.tga")
        lines.append(f"    texture_normals overrides/ab3d2/{name}_n.tga")
        if name in EMISSIVE_TEXTURES:
            lines.append(f"    texture_emissive overrides/ab3d2/{name}_light.tga")
            lines.append("    is_light 1")
            lines.append("    emissive_factor 200")
            lines.append("    bsp_radiance 200")
        lines.append(f"    specular_factor {specular:.2f}")
        lines.append("    metalness_factor 1.0")
        lines.append("    base_factor 1.4")
        lines.append("    bump_scale 0.6")
        lines.append("    correct_albedo 1")
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii")


def build(source_dir: pathlib.Path, out_root: pathlib.Path, normal_strength: float) -> int:
    override_dir = out_root / "baseq2" / "overrides" / "ab3d2"
    material_path = out_root / "baseq2" / "materials" / "ab3d2_pbr.mat"
    names: List[str] = []
    for png_path in sorted(source_dir.glob("*.png")):
        name = png_path.stem
        image = Image.open(png_path).convert("RGBA")
        roughness, metalness = pbr_maps_from_image(image, name)
        names.append(name)
        write_tga(override_dir / f"{name}.tga", pack_alpha(image, roughness))
        write_tga(override_dir / f"{name}_n.tga", normal_from_image(image, normal_strength, metalness))
        write_greyscale_tga(override_dir / f"{name}_r.tga", roughness, image.size)
        write_greyscale_tga(override_dir / f"{name}_m.tga", metalness, image.size)
        if name in EMISSIVE_TEXTURES:
            write_tga(override_dir / f"{name}_light.tga", emissive_from_image(image, name))
    write_materials(material_path, names)
    return len(names)


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert ChatGPT Images 2 PNG textures to Q2RTX PBR overrides")
    parser.add_argument("--source-dir", type=pathlib.Path, default=pathlib.Path("build/q2rtx_pbr_image2/source"))
    parser.add_argument("--out-root", type=pathlib.Path, default=pathlib.Path("build/q2rtx_pbr_image2"))
    parser.add_argument("--normal-strength", type=float, default=3.0)
    args = parser.parse_args()
    count = build(args.source_dir, args.out_root, args.normal_strength)
    print(f"Converted {count} ChatGPT Images 2 textures -> {args.out_root / 'baseq2' / 'overrides' / 'ab3d2'}")
    print(f"Generated materials -> {args.out_root / 'baseq2' / 'materials' / 'ab3d2_pbr.mat'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
