#!/usr/bin/env python3
"""Generate Q2RTX material overrides from the converter's Quake 2 WAL textures."""

from __future__ import annotations

import argparse
import pathlib
import struct
from dataclasses import dataclass
from typing import List, Sequence, Tuple


EMISSIVE_TEXTURES = {"technolights", "floor_0101"}


@dataclass
class WalImage:
    name: str
    width: int
    height: int
    pixels: bytes


def read_pcx_palette(path: pathlib.Path) -> List[Tuple[int, int, int]]:
    data = path.read_bytes()
    if len(data) < 769 or data[-769] != 12:
        raise ValueError(f"{path} does not contain a 256-colour PCX palette")
    pal = data[-768:]
    return [(pal[i], pal[i + 1], pal[i + 2]) for i in range(0, 768, 3)]


def read_wal(path: pathlib.Path) -> WalImage:
    data = path.read_bytes()
    if len(data) < 100:
        raise ValueError(f"{path} is too small to be a WAL")
    raw_name = data[:32].split(b"\0", 1)[0].decode("ascii", "ignore")
    width, height = struct.unpack_from("<ii", data, 32)
    offset = struct.unpack_from("<i", data, 40)[0]
    size = width * height
    if width <= 0 or height <= 0 or offset < 0 or offset + size > len(data):
        raise ValueError(f"{path} has invalid WAL dimensions or mip offset")
    return WalImage(raw_name or path.stem, width, height, data[offset : offset + size])


def write_tga_rgba(path: pathlib.Path, width: int, height: int, pixels: Sequence[Tuple[int, int, int, int]]) -> None:
    header = bytearray(18)
    header[2] = 2
    header[12] = width & 255
    header[13] = (width >> 8) & 255
    header[14] = height & 255
    header[15] = (height >> 8) & 255
    header[16] = 32
    header[17] = 40
    out = bytearray(header)
    for r, g, b, a in pixels:
        out.extend((b, g, r, a))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(out)


def base_pixels(image: WalImage, palette: Sequence[Tuple[int, int, int]]) -> List[Tuple[int, int, int, int]]:
    return [(*palette[index], 255) for index in image.pixels]


def luminance(rgb: Tuple[int, int, int]) -> float:
    r, g, b = rgb
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255.0


def normal_pixels(
    image: WalImage,
    palette: Sequence[Tuple[int, int, int]],
    strength: float,
) -> List[Tuple[int, int, int, int]]:
    width = image.width
    height = image.height
    grey = [luminance(palette[index]) for index in image.pixels]
    out: List[Tuple[int, int, int, int]] = []
    for y in range(height):
        for x in range(width):
            left = grey[y * width + max(0, x - 1)]
            right = grey[y * width + min(width - 1, x + 1)]
            up = grey[max(0, y - 1) * width + x]
            down = grey[min(height - 1, y + 1) * width + x]
            dx = (left - right) * strength
            dy = (up - down) * strength
            nz = 1.0
            length = max((dx * dx + dy * dy + nz * nz) ** 0.5, 1e-6)
            nx = dx / length
            ny = dy / length
            nz /= length
            out.append((
                int((nx * 0.5 + 0.5) * 255),
                int((ny * 0.5 + 0.5) * 255),
                int((nz * 0.5 + 0.5) * 255),
                255,
            ))
    return out


def emissive_pixels(image: WalImage, palette: Sequence[Tuple[int, int, int]]) -> List[Tuple[int, int, int, int]]:
    pixels: List[Tuple[int, int, int, int]] = []
    for index in image.pixels:
        r, g, b = palette[index]
        bright = max(r, g, b)
        if bright >= 72 and (b > r * 1.1 or r > g * 1.2):
            pixels.append((min(255, r * 2), min(255, g * 2), min(255, b * 2), 255))
        else:
            pixels.append((0, 0, 0, 255))
    return pixels


def material_factors(name: str) -> Tuple[float, float, float]:
    lowered = name.lower()
    if lowered.startswith("floor_") or lowered in {"rocky", "stonewall", "brownstonestep"}:
        return 0.95, 0.0, 0.15
    if "metal" in lowered or "techno" in lowered or "door" in lowered or "pipe" in lowered:
        return 0.55, 0.15, 0.65
    return 0.75, 0.0, 0.35


def write_materials(path: pathlib.Path, names: Sequence[str], emissive_names: Sequence[str]) -> None:
    emissive_set = set(emissive_names)
    lines: List[str] = [
        "# Generated by tools/generate_q2rtx_pbr.py",
        "# Q2RTX material overrides for converted AB3D2 textures.",
        "",
    ]
    for name in sorted(names):
        roughness, metalness, specular = material_factors(name)
        lines.append(f"ab3d2/{name},")
        lines.append(f"textures/ab3d2/{name}:")
        lines.append(f"    texture_base overrides/ab3d2/{name}.tga")
        lines.append(f"    texture_normals overrides/ab3d2/{name}_n.tga")
        if name in emissive_set:
            lines.append(f"    texture_emissive overrides/ab3d2/{name}_light.tga")
            lines.append("    is_light 1")
            lines.append("    emissive_factor 200")
            lines.append("    bsp_radiance 200")
        lines.append(f"    roughness_override {roughness:.2f}")
        lines.append(f"    metalness_factor {metalness:.2f}")
        lines.append(f"    specular_factor {specular:.2f}")
        lines.append("    base_factor 1.4")
        lines.append("    bump_scale 0.6")
        lines.append("    correct_albedo 1")
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii")


def generate(wal_dir: pathlib.Path, palette_path: pathlib.Path, out_root: pathlib.Path, normal_strength: float) -> Tuple[int, pathlib.Path]:
    palette = read_pcx_palette(palette_path)
    override_dir = out_root / "baseq2" / "overrides" / "ab3d2"
    material_path = out_root / "baseq2" / "materials" / "ab3d2_pbr.mat"
    names: List[str] = []
    emissive: List[str] = []
    for wal_path in sorted(wal_dir.glob("*.wal")):
        image = read_wal(wal_path)
        name = wal_path.stem
        names.append(name)
        write_tga_rgba(override_dir / f"{name}.tga", image.width, image.height, base_pixels(image, palette))
        write_tga_rgba(override_dir / f"{name}_n.tga", image.width, image.height, normal_pixels(image, palette, normal_strength))
        if name in EMISSIVE_TEXTURES:
            emissive.append(name)
            write_tga_rgba(override_dir / f"{name}_light.tga", image.width, image.height, emissive_pixels(image, palette))
    write_materials(material_path, names, emissive)
    return len(names), material_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Q2RTX PBR override textures for converted AB3D2 WAL files")
    parser.add_argument("--wal-dir", type=pathlib.Path, default=pathlib.Path("build/quake2_assets/baseq2/textures/ab3d2"))
    parser.add_argument("--palette", type=pathlib.Path, default=pathlib.Path("build/quake2_assets/baseq2/pics/colormap.pcx"))
    parser.add_argument("--out-root", type=pathlib.Path, default=pathlib.Path("build/q2rtx_pbr"))
    parser.add_argument("--normal-strength", type=float, default=3.0)
    args = parser.parse_args()
    count, material_path = generate(args.wal_dir, args.palette, args.out_root, args.normal_strength)
    print(f"Generated PBR overrides for {count} textures -> {args.out_root / 'baseq2' / 'overrides' / 'ab3d2'}")
    print(f"Generated materials -> {material_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
